// "use client";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import classNames from "classnames";
import "@/styles/_global.scss";

const montserrat = Montserrat({
  subsets: ["vietnamese"],
  preload: true,
  fallback: ["Quicksand"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 

export default function RootLayout({ children, params, ...props }: any) {
  return (
    <html lang="en">
      <body className={classNames(montserrat.className, "bg-background")}>{children}</body>
    </html>
  );
}
